### ISSUE TITLE
[Bug]: null is not an object (evaluating 'window.open(e,t).focus') on Mobile Safari

### ISSUE THREAD

**Issue by MakarovCode** [add2cal/add-to-calendar-button#329] opened 2023-02-06 15:07 UTC
### What happened?

Getting this issue report on my Sentry dashboard

`if (target == '') {
    target = atcbDefaultTarget;
  }
  if (atcb_secure_url(url)) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    window.open(url, target).focus();
  }
}`

### How to reproduce?

Use the Add to calendar button in Mobile Safari 16.3

### Screenshots & more

![image](https://user-images.githubusercontent.com/1951749/217007894-83bcf195-eaf9-4880-a97f-0c297a92bb37.png)

### System & Environment

Mobile Safari 16.3

**Comment by jekuer** [comment] 2023-02-06 18:47
Can you share more information on the underlying case?
Are you building an iOS app and running the script in a webView environment?

**Comment by jekuer** [comment] 2023-02-13 20:32
Just realized that this is running with an older version of the script.
Closing this, since this should be no longer the case with newer versions.

**Closed by jekuer** 2023-02-13 20:32 UTC
Labels: bug

**Comment by yosephsa** [comment] 2023-03-08 16:21
@jekuer Can you provide the version of the script you were on and which version you upgraded to that resolved the issue? For anyone else coming here about this issue. Thank you!

**Comment by LandonS23** [comment] 2023-07-05 15:55
I also see this error in version 2.2.9 mobile safari when selecting Google Calendar

**Comment by jekuer** [comment] 2023-07-06 05:36
Hi @LandonS23 , Thank you for the input.
Unfortunately, it is really hard to reproduce.
I put a potential fix on dev: Could you maybe retest with the demo at https://blue-field-0efe76003-dev.westeurope.2.azurestaticapps.net/ and see if it fixes the issue?

If not, would be great to see more details regarding your setup.

**Comment by LandonS23** [comment] 2023-07-06 18:35
@jekuer I am not able to reproduce with the above demo, however, I also had trouble reproducing consistently before. We see this error quite a bit in our Datadog so if you feel comfortable deploying the above I could verify we no longer see it after the fix. TIA

**Comment by jekuer** [comment] 2023-07-10 17:51
@LandonS23 , are you using the React wrapper?

**Comment by LandonS23** [comment] 2023-07-10 18:20
@jekuer  I am actually just using `atcb_action` from `add-to-calendar-button` currently

**Comment by jekuer** [comment] 2023-07-10 18:46
@LandonS23 , alright. Just published v2.2.10. If you could test this out and provide feedback about whether this fixed stuff, would be awesome! Thanks.

**Comment by LandonS23** [comment] 2023-07-10 18:47
@jekuer thanks will do

**Comment by LandonS23** [comment] 2023-07-11 15:37
@jekuer can confirm we no longer see the error, thanks for the quick turnaround!
