### ISSUE TITLE
[Bug]: The demo doesnt work on Chrome iOS

### ISSUE THREAD

**Issue by Makio64** [add2cal/add-to-calendar-button#144] opened 2022-08-24 18:24 UTC
### What happened?

The demo doesnt work on Chrome iOS for links other than GoogleCalendar : 
It download the .ics instead of opening the correct app ( Apple iCal / Teams / etc ) 

### How to reproduce?

Open the demo page in Chrome on iOS 

### System & Environment

Iphone 12 Pro , iOS 15.6.1
Chrome latest

**Comment by jekuer** [comment] 2022-08-24 19:46
Unfortunately, this partly is the expected behavior.
There currently is a workaround for Outlook, etc., see https://github.com/add2cal/add-to-calendar-button/discussions/143

However, the problem with the ics file not opening in Safari is a problem. Needs some investigation. No matter the potential solution, Apple is quite bitchy everywhere... 😞

**Comment by jekuer** [comment] 2022-08-25 19:45
Went quite deep into this issue.
Turns out that there is no stable solution to get this optimized (unfortunately). Basically because either Apple or Chrome (on iOS) is not supporting a specific functionality.
For now, the only option is to provide an explicit .ics file (see config options in the readme). This at least triggers a clean ics file download and therefore makes it easy for the users to add it to their calendars.

There are signs that Google might optimize the behavior soon, but not sure about this (see: https://bugs.chromium.org/p/chromium/issues/detail?id=1252380).
I will come up with a better solution over the next months, adding server-side support, since this process is more or less impossible relying only on the client.

Sorry for that update. Will close the issue for now as a won't fix. _(Still, improved the process a tiny little bit with the latest patch release.)_

**Closed by jekuer** 2022-08-25 19:45 UTC
Labels: bug
