### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by r4ks** [add2cal/add-to-calendar-button#173] opened 2022-09-09 13:55 UTC
### What happened?

When modal opens, all cards are above the grey background of modal

### System & Environment

Chome windows 10

**Comment by jekuer** [comment] 2022-09-10 06:53
Hi @r4ks ,

can you specify this a little bit better? Or even add a screenshot?

It is intended behavior that the options are rendered over the background.
If by "cards", you mean other elements on your site, it can get tricky. you might need to update the css.

**Comment by jekuer** [comment] 2022-10-01 15:16
Closing this one, since there was no more information provided and this seems not valid.

**Closed by jekuer** 2022-10-01 15:16 UTC
Labels: invalid
