### ISSUE TITLE
[Bug]: Oxygen Builder fails to load template data with version 2.3

### ISSUE THREAD

**Issue by thisShouldWork** [add2cal/add-to-calendar-button#428] opened 2023-07-27 14:17 UTC
### What happened?

Prior versions of the Add to Calendar Button work flawlessly, but after version 2.3 template data won't load in the Oxygen Builder (version 4.6.2) admin. After disabling the script everything worked again. I pulled the older version 2.2.10 from jsdelivr.com and everything is working again. It appears to be an admin template editor issue only. The front end of the site was unaffected.

### How to reproduce?

Attempt to edit templates in Oxgen Builder 4.6.2 with Add to Calendar Button 2.3 enabled. Templates fail to load.

### System & Environment

Macbook Pro running Ventura.
Chrome 114.0.5735.248 and Firefox 115.0.2
Oxygen Builder 4.6.2 and Add to Calendar Button 2.3
Script loaded from [cdn](https://www.jsdelivr.com/)

**Comment by jekuer** [comment] 2023-07-27 15:29
@thisShouldWork , did you try the official WordPress plugin?
https://wordpress.org/plugins/add-to-calendar-button/

**Comment by thisShouldWork** [comment] 2023-07-27 19:12
Thanks for checking in. Here are screenshots of the admin and console. Just to test it for you I tried the WP plugin with the same results. I like using the jsdelivr method via WPCodebox since it's one less plugin to manage though. Attached are screenshots of the admin and console. It's working again under 2.2.10. Not sure what you'll be able to tell from these, but here they are.

Oxygen Admin with 2.3 active
<img width="1728" alt="Oxygen Admin with 2 3 active" src="https://github.com/add2cal/add-to-calendar-button/assets/5858452/97dcbc2d-4a21-4f98-aa41-3359a234909f">

2.3 Active Console
<img width="1728" alt="Oxygen Admin with 2 3 active - Console" src="https://github.com/add2cal/add-to-calendar-button/assets/5858452/9047dac7-59b7-4999-8c86-5fafd5c346b8">

2.3 Using Official WP Plugin
<img width="1728" alt="Oxygen Admin with 2 3 loaded through WP plugin" src="https://github.com/add2cal/add-to-calendar-button/assets/5858452/44f00a63-115e-4ea9-b791-ec4ff783f6f7">

2.2.10 Active in WPCodebox
<img width="1728" alt="Version 2 2 10 loaded via WPCodebox" src="https://github.com/add2cal/add-to-calendar-button/assets/5858452/6e728b00-a7a6-470e-84cd-2d9978d43f5f">

Oxygen Admin with 2.2.10 active - Console
<img width="1728" alt="Oxygen Admin with 2 2 10 loaded via WPCodebox" src="https://github.com/add2cal/add-to-calendar-button/assets/5858452/de5cb4c3-1b26-4e89-8d21-5f37fdcbc74f">

**Comment by jekuer** [comment] 2023-07-27 19:26
Thanks a lot!
Hoped for some clear issue, but no "luck", unfortunately.
Will need to try to rebuild your stack for further testing. Will take a while.

**Comment by jekuer** [comment] 2023-07-28 16:08
@thisShouldWork , maybe some more things to try:

1. Does it change something to se the snippet order to something like 80?
2. Could you try removing the button (your html, not the snippet), upgrade the version, then add the code again (with the Gutenberg block, there sometimes is some kind of caching issue on updates - maybe it is similar with Oxygen)
3. Can you share the HTML of the button?
4. If all of this is not working, any chance to get access to the system for me?

**Comment by jekuer** [comment] 2023-08-08 09:53
Hi @thisShouldWork ,

any progress on your side?

**Comment by KeanuTang** [comment] 2023-08-16 18:36
I am also having issues with the plugin and Oxygen Builder. It's a different error than what was reported here. The JavaScript error goes away when I deactivate the plugin. 

![image](https://github.com/add2cal/add-to-calendar-button/assets/121991155/d9e08952-5395-4ce6-b2a1-87ace43d272c)

**Comment by jekuer** [comment] 2023-08-16 21:01
Hi @KeanuTang & @thisShouldWork ,

the latest release (v2.3.3 - v1.3.3 if using the WP Plugin) comes with some renaming and capsuling of global variables. Assuming that that's the cause, it could fix your issues.
Would be awesome if you could test and put some feedback here!

Thanks!
Jens

**Comment by thisShouldWork** [comment] 2023-08-16 21:25
@jekuer So I was triggering the code from a custom button. Has the advanced usage code changed from using atcb_action(config, button)?

The 2.3.3 code isn't breaking Oxygen loading on the backend anymore, but the code isn't working on the front end using the custom button configuration [shown at #10 here](https://add-to-calendar-button.com/advanced-use).

**Comment by KeanuTang** [comment] 2023-08-16 23:41
> Hi @KeanuTang & @thisShouldWork ,
> 
> the latest release (v2.3.3 - v1.3.3 if using the WP Plugin) comes with some renaming and capsuling of global variables. Assuming that that's the cause, it could fix your issues. Would be awesome if you could test and put some feedback here!
> 
> Thanks! Jens

1.3.3 for WP works for me! Thanks!

**Comment by jekuer** [comment] 2023-08-17 05:58
@thisShouldWork , sorry for that. The fix excluded the function from being accessible - fixed with another patch.
Closing the issue for now. In case there are still problems, please comment and I will re-open it. Thanks!

**Closed by jekuer** 2023-08-17 05:58 UTC
Labels: bug, question

**Comment by thisShouldWork** [comment] 2023-08-17 14:48
@jekuer You're a genius! Works perfectly! Thank you!
