### ISSUE TITLE
[Bug]: Microsoft 365 not working

### ISSUE THREAD

**Issue by klaus-gsma** [add2cal/add-to-calendar-button#486] opened 2023-10-16 08:21 UTC
### What happened?

The link stays on an animation of an envelope opening. To fix this the `0/` between `calendar/` and `Dee-link` needs to be removed, i.e.:

https://outlook.office.com/calendar/0/deeplink/compose?...

### How to reproduce?

Use the Microsoft 365 target with an even, example generated link:

https://outlook.office.com/calendar/0/deeplink/compose?path=%2Fcalendar%2Faction%2Fcompose&rru=addevent&startdt=2023-10-17T07%3A30%3A00Z&enddt=2023-10-17T08%3A45%3A00Z&subject=Keynote%201%3A%20Digitalisation%20of%20Everything&location=Main%20Building%2C%20The%20Auditorium&body=With%20the%20world’s%20youngest%20population%2C%20demand%20for%20digitalisation%20across%20Africa%20has%20grown%20at%20its%20fastest%20pace%20through%20rapid%20urbanization%20and%20a%20huge%20increase%20in%20the%20consumption%20of%20online%20services.%20And%20at%20a%20time%20when%20technological%20innovation%20and%20economic%20growth%20go%20together%2C%20technologies%20such%20as%20Generative%20AI%20represent%20a%20major%20opportunity%20to%20transform%20telecom%20businesses%20and%20services.%20Intelligent%20connectivity%20is%20opening%20opportunities%20for%20new%20partnerships%20and%20innovation%20but%20only%20if%20high-quality%20access%20to%20communication%20networks%20and%20services%20are%20made%20available%20to%20all%2C%20and%20at%20affordable%20prices.%20Join%20us%20as%20we%20hear%20from%20the%20leaders%20across%20the%20region%20on%20their%20role%20in%20creating%20our%20digitally%20connected%20future.&uid=7415751b-49b5-4dbc-a0fa-dea8dab672d1

### Screenshots & more

<img width="479" alt="Screenshot 2023-10-16 at 09 19 30" src="https://github.com/add2cal/add-to-calendar-button/assets/57663451/8bf6ed58-e734-4f18-bdb2-a50a0b86cfdc">

Thread on this issue:

https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-365-add-to-calendar-link-not-working-did/b28e3a34-5e24-46f7-a5a1-24ce62a60e42

### System & Environment

Tested on multitude of browsers and OS versions (Windows, MacOS, iOS)

**Comment by jekuer** [comment] 2023-10-18 07:47
Hi Klaus,

Thanks a lot for your contribution!
Unfortunately, I was not able to reproduce this.

As you might have seen in the code, we only use the mentioned scheme for mobile devices.
For desktop, we use https://outlook.office.com/calendar/action/compose/?rru=addevent?... - we changed this when MS updated their internal routing beginning of this year. Simply removing the 0 led to some other side effects back then.

On mobile devices, the new scheme does not work, but the old one does - with and without the 0.

**Therefore, my question:**
Could maybe explain in a little more detail, where you are experiencing the issue?

- Which device, which OS, what browser (1 case might be enough)?
- Also the version of the script you are using.
- And what would also be helpful: When calling the link, are you already logged into your MS365 account or not?

Thanks a lot in advance!
Jens

**Comment by jekuer** [comment] 2023-11-06 16:56
@klaus-gsma , were you able to reproduce and share the mentioned details?
Otherwise, I would close this issue for now, as (even MS has build some redirection hell on their side) there is no bug or room for improvement on our side.

**Closed** 2023-11-06 16:58 UTC
Labels: bug, question

**Comment by jekuer** [comment] 2023-11-06 17:00
Still, thanks a lot for contributing! 😃
