### ISSUE TITLE
[Bug]: Add multiple events in iPhone calender fails (React PWA)

### ISSUE THREAD

**Issue by stha2024** [add2cal/add-to-calendar-button#525] opened 2023-12-26 11:24 UTC
### What happened?

Multiple buttons on page with different calender entries on one page. When I press the first button, the event is is put into the calender an everything is OK. But when I press the next button for a new calender entry the previous one pops up. If I delete the first calender entry, an press button once again,then the second one will be entered into calender.

### How to reproduce?

`          <AddToCalendarButton 
            styleLight="--btn-background: #2f4377; --btn-text: #fff; --font: Georgia, 'Times New Roman', Times, serif;"
            styleDark="--btn-background: #000;"
            lightMode="dark"
            name={calenderName(data.dato)}
            uid={calenderUid()}
            options={['Apple', 'Google', 'iCal', 'Microsoft365', 'MicrosoftTeams', 'Outlook.com','Yahoo']}
            location={data.merknad}
            startDate={calenderDate(data.dato)}
            endDate={calenderDate(data.dato)}
            startTime="19:00"
            endTime="23:59"
            label="+Kalender"
            size="1/1/1"
            timeZone="currentBrowser"
            description="[p][strong]NB![/strong] [/p]
        ></AddToCalendarButton>`

### Screenshots & more

![image](https://github.com/add2cal/add-to-calendar-button/assets/154886567/32fc3398-f1dc-4250-b739-23a73bab156f)

### System & Environment

iOS 17.2.1, Chrome 119.0.6045.199, add-to-calender-button-react 2.5.4, MacBookAir macOS Sonoma ver. 14.1.2, Safari 17.1.2

**Comment by jekuer** [comment] 2023-12-26 13:48
Hi @stha2024 ,

Is it also that way when using hard coded values instead of the data bindings?

**Comment by stha2024** [comment] 2023-12-26 22:57
No changes with hardcoded values. The detail screen for the first atcb is popping up if I press the second atcb button. And if I added the second event to calender, and press the first atcb button, the second text appear in detail screen.

`      <AddToCalendarButton
        name="[Reminder - 1] Test the Add to Calendar Button"
        startDate="2023-12-30"
        startTime="10:15"
        endTime="23:30"
        timeZone="America/Los_Angeles"
        location="World Wide Web"
        description="Check out the maybe easiest way to include Add to Calendar Buttons to your web projects:[br]→ [url]https://add-to-calendar-button.com/"
        options={['Apple', 'Google', 'iCal', 'Microsoft365', 'MicrosoftTeams', 'Outlook.com','Yahoo']}
        lightMode="bodyScheme"
      ></AddToCalendarButton>

      <AddToCalendarButton
        name="[Reminder - 2] Test the Add to Calendar Button"
        startDate="2023-12-31"
        startTime="10:15"
        endTime="23:30"
        timeZone="America/Los_Angeles"
        location="World Wide Web"
        description="Check out the maybe easiest way to include Add to Calendar Buttons to your web projects:[br]→ [url]https://add-to-calendar-button.com/"
        options={['Apple', 'Google', 'iCal', 'Microsoft365', 'MicrosoftTeams', 'Outlook.com','Yahoo']}
        lightMode="bodyScheme"
      ></AddToCalendarButton>`

**Comment by jekuer** [comment] 2023-12-27 10:07
confirmed.

Seems to be very Apple specific.
So, nothing directly wrong with the code. More like Apple seems to have changed something or introduced a new bug on their side.
Will dig deeper...

**Comment by jekuer** [comment] 2023-12-27 17:38
Fixed on dev.
Reason: Apple seems to have optimized the UID support while there was a small bug making uid "undefined", if not set, which made Apple think it's the same event each time.

Fix will be released very soon.

In your original post, I saw that you also use the UID. Make sure this is unique for each event.

**Comment by stha2024** [comment] 2023-12-27 17:40
Thanks :), perfect now.

**Closed** 2023-12-28 19:49 UTC
Labels: bug
